#!/bin/sh
if [ -d /sys/firmware/efi ]; then
  BIOS="-bios /usr/share/OVMF/OVMF_CODE.fd"
else
  BIOS=""
fi

DRIVES=$(
  lsblk --include 8,259 --json --paths | 
  jq -r '.blockdevices | sort_by(.name) | .[].name | "-drive file=\(.),format=raw,if=virtio"'
)

qemu-system-x86_64 \
  -enable-kvm \
  -cpu host \
  -m 16G \
  $DRIVES \
  $BIOS \
  -vnc 127.0.0.1:0 \
  -boot d \
  -cdrom ./proxmox.iso \
  #

